export { Login } from './LogIn'
export { Register } from './Register'
export { NavBar } from './NavBar'
export { AuthFeedback } from './AuthFeedback'
export { AdminEnemigos } from './AdminEnemigos'
export { AdminUsuarios } from './AdminUsuarios'
export { AdminHistorial } from './AdminHistorial'
export { AdminNuevoAdmin } from './AdminNuevoAdmin'